server:
  port: 8102
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: mcp-server-weixin
  main:
    banner-mode: off
    # stdio 模式打开，sse 模式，注释掉。
    # web-application-type: none
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0

weixin:
  api:
    original_id: gh_7825781c72bd
    app-id: wxf155bfa65b4d862e
    app-secret: ce91ae00e94c049001d8bb7bdc5bcd7f
    template_id: bprFVxBf9NHwoUXyAbIxNrhLGU55jsnFi1aNoHxebyo
    touser: o_9Y9vhED_5nSonj-QTzGPRH4XQE

logging:
  # stdio 模式打开，sse 模式，注释掉。
#  pattern:
#    console:
  file:
    name: data/log/${spring.application.name}.log


